<?php

declare(strict_types=1);
/**
 * DuckPhp
 *
 * Main entry of this skeleton project. You normally do not edit this file.
 * Change behavior by editing the options in $options below.
 *
 * Extends DuckPhp\DuckPhp and sets the project path, error views,
 * controller prefix, and optional CLI command or exception reporter classes.
 */

namespace YourProjectName\System;

use DuckPhp\DuckPhp;
use YourProjectName\Controller\ConsoleCommand;

class App extends DuckPhp
{
    //@override
    public $options = [
        'path' => __DIR__ . '/../../',                              // project root
        //'path_info_compact_enable' => false,                      // use this if PATH_INFO is not available

        'error_404' => '_sys/error_404',                            // 404 view
        'error_500' => '_sys/error_500',                            // 500 view

        //'controller_method_prefix' => '',                    // method prefix for controllers
        // 'controller_resource_prefix' => '',                         // used by `__res()` helper

        // 'cli_command_classes' => [ConsoleCommand::class],          // add to enable `php ./cli.php hello`
        // 'cli_command_with_common' => true,                          // also show built-in CLI commands

        // 'exception_reporter' => ExceptionReporter::class,        // turn on to use the custom reporter
        // 'exception_for_project' => ProjectException::class,        // reporter only handles this class and its subclasses
        // 'exception_for_business' => BusinessException::class,      // extends ProjectException; thrown by Helper::BusinessThrowOn()
        // 'exception_for_controller' => ControllerException::class,  // extends ProjectException; thrown by Helper::ControllerThrowOn()

        // ... see options.md for more
    ];
    //@override
    protected function onInited()
    {
        parent::onInited();
        // add your init code here
    }
}
