version: "3"

services:
  fulltest84:
    build:
      context: ../..
      dockerfile: docker/test-php84/Dockerfile
    working_dir: /DATA
    volumes:
      - ../../:/DATA
      - ./test_reports:/DATA/test_reports
      - ./test_coveragedumps:/DATA/test_coveragedumps
      - ../../composer-test-php84.json:/DATA/composer.json
      - ../../composer-test-php84.lock:/DATA/composer.lock
      - vendor84:/DATA/vendor
      - ../../docker/test-php84/libcoverage:/DATA/vendor/dvaknheo/libcoverage
      - composer-cache84:/tmp/composer
    entrypoint:
      - /bin/sh
      - -c
      - redis-server --requirepass 123456 --save "" --appendonly no --daemonize yes && exec "$$@"
      - docker-entrypoint
    environment:
      - COMPOSER_HOME=/tmp/composer
      - XDEBUG_MODE=coverage
    extra_hosts:
      - "redis:127.0.0.1"
    command: >
      sh -c "
        ([ -f /DATA/vendor/autoload.php ] || composer install --no-interaction --prefer-dist) &&
        composer run-script --timeout=0 fulltest
      "

volumes:
  composer-cache84:
  vendor84:
