version: "3"

services:
  fulltest:
    image: duckphp/test-php74:latest
    build:
      context: ../..
      dockerfile: docker/test-php74/Dockerfile
    working_dir: /DATA
    volumes:
      - ../../:/DATA
      - vendor:/DATA/vendor
      - composer-cache:/tmp/composer
      - ./test_reports:/DATA/test_reports
      - ./test_coveragedumps:/DATA/test_coveragedumps
    entrypoint:
      - /bin/sh
      - -c
      - redis-server --requirepass 123456 --save "" --appendonly no --daemonize yes && exec "$$@"
      - docker-entrypoint
    environment:
      - COMPOSER_HOME=/tmp/composer
      - XDEBUG_MODE=coverage
    extra_hosts:
      - "redis:127.0.0.1"
    command:
      - sh
      - -c
      - |
        cd /DATA &&
        rm -f /DATA/composer.lock &&
        composer update --no-interaction --prefer-dist --no-scripts &&
        composer exec phpunit
volumes:
  composer-cache:
  vendor:
  data-for-tests74:
