version: "3"

services:
  fulltest:
    build:
      context: ../..
      dockerfile: docker/test-php74/Dockerfile
    working_dir: /DATA
    volumes:
      - ../../:/DATA
      - ../../composer-test-php74.json:/DATA/composer.json
      - ../../composer-test-php74.lock:/DATA/composer.lock
      - vendor:/DATA/vendor
      - composer-cache:/tmp/composer
    entrypoint:
      - /bin/sh
      - -c
      - redis-server --requirepass 123456 --daemonize yes && exec "$$@"
      - docker-entrypoint
    environment:
      - COMPOSER_HOME=/tmp/composer
    extra_hosts:
      - "redis:127.0.0.1"
    command: >
      sh -c "
        ([ -f /DATA/vendor/autoload.php ] || composer install --no-interaction --prefer-dist) &&
        composer run-script --timeout=0 fulltest
      "

volumes:
  composer-cache:
  vendor:
