version: "3"

services:
  fulltest:
    build: .
    working_dir: /DATA
    volumes:
      - ../../:/DATA
      - vendor:/DATA/vendor
      - composer-cache:/tmp/composer
    environment:
      - COMPOSER_HOME=/tmp/composer
    extra_hosts:
      - "redis:127.0.0.1"
    command: >
      sh -c "
        redis-server --requirepass 123456 --daemonize yes &&
        cp docker/test-php74/composer.lock.docker composer.lock &&
        ([ -f /DATA/vendor/autoload.php ] || composer install --no-interaction --prefer-dist) &&
        composer run-script --timeout=0 fulltest
      "

volumes:
  composer-cache:
  vendor:
