<?php declare(strict_types=1);
/**
 * DuckPhp
 * From this time, you never be alone~
 */
namespace DuckPhp\Component;

use DuckPhp\Core\App;
use DuckPhp\Core\ComponentBase;

class ExtOptionsLoader extends ComponentBase
{
	public $options = [
        'path' => null,
		'path_installed_options' => 'config',
        'installed_options_file' => 'DuckPhpInstalled.config.php',
	];
    public static $all_ext_options;
 
 
	public function getOptionFilePath()
	{
		$file = $this->extendFullFile($this->options['path'], $this->options['path_installed_options'], $this->options['installed_options_file']);
		return $file;
        //$full_file = realpath($file);
	}
	public function refreshData($data)
	{
		$file = $this->extendFullFile($this->options['path'], $this->options['path_installed_options'], $this->options['installed_options_file']);
        $full_file = realpath($file);
        if (!$full_file) {
            $ext_options = [];
        } else {
			$ext_options = (function ($file) {
				return require $file;
			})($full_file);
		}
		
		$options = array_replace_recursive($ext_options, $data);
		
		$string = "<"."?php //". "regenerated by " . __CLASS__ . '->'.__FUNCTION__ ." at ". DATE(DATE_ATOM) . "\n";
        $string .= "return ".var_export($options, true) .';';
        file_put_contents($file, $string);
		
		clearstatcache();
	}
    public function loadExtOptions($force = false, $class = null)
    {
		if ($class) {
			$this->init($class->options,$class);
		}
        $full_file = $this->extendFullFile($this->options['path'], $this->options['path_installed_options'], $this->options['installed_options_file']);
        $full_file = realpath($full_file);
        if (!$full_file) {
            return;
        }
        $ext_options = (function ($file) {
            return require $file;
        })($full_file);
		
		return $ext_options;
    }
    public function saveExtOptions($options, $class = null)
    {
		if ($class) {
			$this->init($class->options,$class);
		}
        $full_file = $this->extendFullFile($this->options['path'], $this->options['path_installed_options'], $this->options['installed_options_file']);
        $string = "<"."?php //". "regenerate by " . __CLASS__ . '->'.__FUNCTION__ ." at ". DATE(DATE_ATOM) . "\n";
        $string .= "return ".var_export($options, true) .';';
        file_put_contents($full_file, $string);
        
        clearstatcache();
    }
}
