<?php declare(strict_types=1);
/**
 * DuckPhp
 * From this time, you never be alone~
 */
namespace DuckPhp\Component;

use DuckPhp\Core\App;
use DuckPhp\Core\ComponentBase;

class ExtOptionsLoader extends ComponentBase
{
    public $options = [
        'path' => null,
        'path_installed_options' => 'config',
        'installed_options_file' => 'DuckPhpInstalled.config.php',
    ];

 
    public function getOptionFilePath()
    {
        if ($this->isInited()) {
            $this->init(App::Current()->options, App::Current());
        };
        $file = $this->extendFullFile($this->options['path'], $this->options['path_installed_options'], $this->options['installed_options_file']);
        return $file;
        //$full_file = realpath($file);
    }
    public function refreshData($data)
    {
        if ($this->isInited()) {
            $this->init(App::Current()->options, App::Current());
        };
        $file = $this->extendFullFile($this->options['path'], $this->options['path_installed_options'], $this->options['installed_options_file']);
        $full_file = realpath($file);
        if (!$full_file) {
            $ext_options = [];
        } else {
            $ext_options = (function ($file) {
                return require $file;
            })($full_file);
        }
        
        $options = array_replace_recursive($ext_options, $data);
        
        $string = "<"."?php //". "regenerated by " . __CLASS__ . '->'.__FUNCTION__ ." at ". DATE(DATE_ATOM) . "\n";
        $string .= "return ".var_export($options, true) .';';
        file_put_contents($file, $string);
        
        clearstatcache();
    }
    public function checkInstallStatus()
    {
        $class = $this->content()->getOverridingClass();
        $file = str_replace('\\', '.',$class);
        
        $has_config_file = is_file($config_file);
        $has_runtime_file = is_file($runtime_file);
        
        if($has_config_file){
            if($has_runtime_file){
                //remove runtime file
                // log it
            }
            return;
        }
        
        if (!$has_config_file && !$has_runtime_file){
            //goto install;
        }
        
        
        if (!$has_config_file && $has_runtime_file){
            //goto exception
        }
        
    }
}
